pipeline {
    agent { label 'slave' }  // This locks the CD job to run only on Slave_A

    environment {
        IMAGE_NAME = "varun1411/ci_cd"
        CONTAINER_NAME = "ci_cd_container"
    }

    stages {

        stage('Pull Latest Docker Image') {
            steps {
                script {
                    sh "docker pull ${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Stop and Remove Old Container (if running)') {
            steps {
                script {
                    sh "docker stop ${CONTAINER_NAME} || true"
                    sh "docker rm ${CONTAINER_NAME} || true"
                }
            }
        }

        stage('Run New Container') {
            steps {
                script {
                    sh "docker run -d --name ${CONTAINER_NAME} -p 3000:3000 ${IMAGE_NAME}:latest"
                }
            }
        }
    }
}
