pipeline {
    agent any

    environment {
        IMAGE_NAME = "discoverdevops/micro_service"
        CONTAINER_NAME = "micro_service_container"
    }

    stages {

        stage('Pull Latest Docker Image') {
            steps {
                script {
                    sh "docker pull ${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Stop and Remove Old Container (if running)') {
            steps {
                script {
                    // Stop the old container if running (ignore error if not running)
                    sh "docker stop ${CONTAINER_NAME} || true"
                    sh "docker rm ${CONTAINER_NAME} || true"
                }
            }
        }

        stage('Run New Container') {
            steps {
                script {
                    sh """
                    docker run -d --name ${CONTAINER_NAME} -p 3000:3000 ${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }
}
